
#############################################################
########## LOCAL Environment ################################
#############################################################
spring:
   profiles: LOCAL
   datasource:
      url: jdbc:mysql://localhost:3306/onlinemess?useSSL=false
      username: root
      password: Dhanraj_1234

server:
   port: 8080
   tomcat:
      max-threads: 500
      max-connections: 500

toptal.security.jwt:
   tokenExpirationTime: 15 # Number of minutes
   refreshTokenExpTime: 60 # Minutes
   tokenIssuer: http://dhanrajpurbiya.com
   tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus
